### ISSUE TITLE
drop log level CRITICAL

### ISSUE THREAD

**Issue by wusphinx** [devopsfaith/krakend-gologging#8]
Mainstream logging frameworks such as [zap](https://github.com/uber-go/zap) and [logrus](https://github.com/sirupsen/logrus) have no log level `CRITICAL` except krakend-gologging, this means I can't use the logging framework mentioned above, so maybe you can consider removing the Critical level

**Comment by kpacha** [comment]
Once published, we can't remove a method from an interface. That would break the contract.

If you want to use other loggers, just create a wrapper implementing the interface.

``` 
type Logger struct {
	logger *xyz.Logger // your actual logger
}

func (l Logger) Debug(v ...interface{}) {
	l.logger.Debug(v...)
}

func (l Logger) Info(v ...interface{}) {
	l.logger.Info(v...)
}

func (l Logger) Warning(v ...interface{}) {
	l.logger.Warning(v...)
}

func (l Logger) Error(v ...interface{}) {
	l.logger.Error(v...)
}

func (l Logger) Critical(v ...interface{}) {
	// do whatever...
}

func (l Logger) Fatal(v ...interface{}) {
	l.logger.Fatal(v...)
}
```
